# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='title',
            field=models.CharField(default='N/A', max_length=200),
            preserve_default=False,
        ),
    ]
