# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkn', '0002_simulation_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation',
            old_name='created_date',
            new_name='published_date',
        ),
    ]
