# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pkn', '0003_auto_20170918_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
